<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Test script is Fail]]>
    </line>
  </reporter-output>
  <suite started-at="2025-05-06T09:06:01 IST" name="Default suite" finished-at="2025-05-06T09:06:11 IST" duration-ms="9426">
    <groups>
    </groups>
    <test started-at="2025-05-06T09:06:01 IST" name="Default test" finished-at="2025-05-06T09:06:11 IST" duration-ms="9426">
      <class name="Listeners.TestScript">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:Listeners.TestScript@7e6f74c]" started-at="2025-05-06T09:06:01 IST" name="openBrowser" finished-at="2025-05-06T09:06:09 IST" duration-ms="7366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="login()[pri:0, instance:Listeners.TestScript@7e6f74c]" started-at="2025-05-06T09:06:09 IST" name="login" finished-at="2025-05-06T09:06:10 IST" duration-ms="1700" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home page is not displayed expected [Demo Web Shop] but found [Demo Web Shop. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home page is not displayed expected [Demo Web Shop] but found [Demo Web Shop. Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at Listeners.TestScript.login(TestScript.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test script is Fail]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- Listeners.TestScript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
